config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  root to:'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'admin' => 'admin/homes#top'

  # 管理者側のルーティング設定
  namespace :admin do
    # get 'items' => 'items#index'
    # post 'items' => 'items#create'
    # get 'items/new' => 'items#new'
    # get 'items/:id' => 'items#show'
    # get 'items/:id/edit' => 'items#edit'
    # patch 'items/:id' => 'items#update'
    resources :items,except:[:destroy]
  end

  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show]
    resources :genres,only: [:index,:create,:edit,:update]
  end

  scope module: :public do
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
  patch 'customers/withdraw' => 'customers#withdraw'
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/complete' => 'orders#complete'

  resources :items,only: [:index,:show]
  resources :cart_items,only: [:index,:create,:destroy,:update]
  resources :orders,only: [:index,:show,:create,:new]
  resources :addresses,only: [:index,:create,:edit,:destroy,:update]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :orders
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
has_many :items


end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_items
  belongs_to :genre
  # enum sales_status: { sale: true, stop_sale: false }

   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end

   TAX_RATE = 0.1
   def tax_included_price
    (price * (1 + TAX_RATE)).floor
   end

   def with_tax_price
       (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
      purchase_price * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
  # ストロングパラメータ
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @new_genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @item = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @item_new = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name,:image,:introduction,:price,:genre_id,:sales_status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total_price = 0
  end

  private
  def order_params
    params.require(:order).permit(:billing_amount,:customer_id,:payment_method,:delivery_postal_code,:delivery_address,:delivery_name)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/app/admin_helper.rb
module App::AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto">

      <h4 class="mt-5 mb-4"><%= @customer.last_name+@customer.first_name %>さんの会員情報編集</h4>
      <table>
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <%= form_with model: @customer,url: admin_customer_path do |f| %>
      <tr>
       <th><label for="inputName">氏名</label></th>
       <td><%= f.text_field :last_name, autofocus: true %></td>
       <td><%= f.text_field :first_name %></td>
      </tr>
      <tr>
        <th><label for="inputName">フリガナ</label></th>
        <td><%= f.text_field :last_name_kana %></td>
        <td><%= f.text_field :first_name_kana %></td>
      </tr>
      <tr>
        <th><label for="inputCode">郵便番号</label></th>
        <td><%= f.text_field :postal_code %></td>
      </tr>
      <tr>
        <th><label for="inputAddress">住所</label></th>
        <td><%= f.text_field :address %></td>
      </tr>
      <tr>
        <th><label for="inputCode">電話番号</label></th>
        <td><%= f.text_field :postal_code %></td>
      </tr>
      <tr>
        <th><label for="inputEmail">メールアドレス</label></th>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
        <th><label for="inputStatus">会員ステータス</label></th>
        <td>
        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted,"有効" %>
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted,"退会" %></td>
      </tr>
      </table>
       <span><%= f.submit "変更を保存",class: 'btn btn-success' %></span>
       <% end %>
  </div>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto">

  <h4 class="mt-5 mb-4">会員一覧</h4>

    <table class="w-100 table">
      <tr>
       <th>会員ID</th>
       <th>氏名</th>
       <th>メールアドレス</th>
       <th>ステータス</th>
      </tr>
      <% @customers.each do |customer| %>
      <tr>
       <td><%= customer.id %></td>
       <td><%= link_to customer.last_name+customer.first_name,admin_customer_path(customer.id),class: 'text-dark' %></td>
       <td><%= customer.email %></td>
           <% if customer.is_deleted == true %>
           <td class="text-black-50">退会</td>
           <% else %>
           <td class="text-success">有効</td>
           <% end %>
      </tr>
      <% end %>
    </table>
    <%= paginate @customers %>

  </div>
 </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto">

  <h4 class="mt-5 mb-4"><%= @customer.last_name+@customer.first_name %>さんの会員詳細</h4>
  <table class="table">
    <tr>
      <th>会員ID</th>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td><%= @customer.last_name+@customer.first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= @customer.last_name_kana+@customer.first_name_kana %></td>
    </tr>
    <tr>
     <th>郵便番号</th>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
           <% if @customer.is_deleted == true %>
           <td class="text-black-50">退会</td>
           <% else %>
           <td class="text-success">有効</td>
           <% end %>
    </tr>
  </table>

  <span><%= link_to "編集する",edit_admin_customer_path,class: 'btn btn-success' %></span>

  </div>
 </div>
</div>