config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  root to:'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'admin' => 'admin/homes#top'

  # 管理者側のルーティング設定
  namespace :admin do
    # get 'items' => 'items#index'
    # post 'items' => 'items#create'
    # get 'items/new' => 'items#new'
    # get 'items/:id' => 'items#show'
    # get 'items/:id/edit' => 'items#edit'
    # patch 'items/:id' => 'items#update'
    resources :items,except:[:destroy]
  end

  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show]
    resources :genres,only: [:index,:create,:edit,:update]
  end

  scope module: :public do
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
  patch 'customers/withdraw' => 'customers#withdraw'
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/complete' => 'orders#complete'

  resources :items,only: [:index,:show]
  resources :cart_items,only: [:index,:create,:destroy,:update]
  resources :orders,only: [:index,:show,:create,:new]
  resources :addresses,only: [:index,:create,:edit,:destroy,:update]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :orders
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
has_many :items


end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_items
  belongs_to :genre
  # enum sales_status: { sale: true, stop_sale: false }

   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end

   TAX_RATE = 0.1
   def tax_included_price
    (price * (1 + TAX_RATE)).floor
   end

   def with_tax_price
       (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
      purchase_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @new_genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @item = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @item_new = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name,:image,:introduction,:price,:genre_id,:sales_status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total_price = 0
  end

  private
  def order_params
    params.require(:order).permit(:billing_amount,:customer_id,:payment_method,:delivery_postal_code,:delivery_address,:delivery_name)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/app/admin_helper.rb
module App::AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <h4 class="mt-5 mb-4">注文履歴一覧</h4>

    <table class="w-100 table">
      <tr>
       <th>購入日時</th>
       <th>購入者</th>
       <th>注文個数</th>
      </tr>
      <% @orders.each do |order| %>
      <tr>
       <td><%= link_to order.created_at,admin_order_path(order.id),class: 'text-dark' %></td>
       <td><%= order.customer.last_name %>
           <%= order.customer.first_name %>
       </td>
       <td><%= order.order_items.sum(:amount) %></td>
      </tr>
      <% end %>
    </table>
    <%= paginate @orders %>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto">

   <h4 class="mt-5 mb-4">商品編集</h4>
     <%= form_with model: @item,url:admin_item_path,method: :patch do |f| %>
     <table>
     <tr>
       <th><label for="inputImage">商品画像</label>
       <%= f.file_field :image, placeholder: "商品画像", accept: "image/*" %>
       </th>
     </tr>
     <tr>
         <th><label for="inputName">商品名</label>
         <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"商品名"%>
         </th>
     </tr>
     <tr>
         <th><label for="inputIntroduction">商品説明</label>
         <%= f.text_area :introduction, placeholder: "商品説明" %>
         </th>
     </tr>
     <tr>
         <th><label for="inputGenreName">ジャンル</label>
         <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_name) %>
         </th>
     </tr>
     <tr>
         <th><label for="inputPrice">税抜価格</label>
         <%= f.number_field :price, placeholder: "税抜価格" %>円
         </th>
     </tr>
     <tr>
         <th><label for="inputPrice">販売ステータス</label>
          <%= f.radio_button :sales_status, true %>
          <%= f.label :sales_status,"販売中" %>
          <%= f.radio_button :sales_status, false %>
          <%= f.label :sales_status,"販売停止中" %></th>
     </tr>
     <tr>
         <th><%= f.submit "変更を保存",class: 'btn btn-success' %></th>
         <% end %>
     </tr>
     </table>
 </div>
</div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <h4 class="mt-5 mb-4">商品一覧</h4>

  <div class="text-right"><%= link_to "+", new_admin_item_path,class: 'text-dark' %></div>
    <table class="w-100 table">
      <tr>
       <th>商品ID</th>
       <th>商品名</th>
       <th>税抜価格</th>
       <th>ジャンル</th>
       <th>ステータス</th>
      </tr>
      <% @item.each do |item| %>
      <tr>
       <td><%= item.id %></td>
       <td><%= link_to item.name,admin_item_path(item.id),class: 'text-dark' %></td>
       <td><%= item.price %></td>
       <td><%= item.genre.genre_name %></td>
       <td><% if item.sales_status == true %>
           <td class="text-success">販売中</td>
           <% else %>
           <td class="text-black-50">販売停止中</td>
           <% end %></td>
      </tr>
      <% end %>
    </table>
    <%= paginate @item %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto">

<h4 class="mt-5 mb-4">商品新規登録</h4>
  <%= form_with model: @item,url:admin_items_path do |f| %>
  <table>
    <tr>
      <th>商品画像</th>
      <td><%= f.file_field :image, accept: "image/*" %></td>
    </tr>
    <tr>
      <th>商品名</th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>商品説明</th>
      <td><%= f.text_area :introduction %></td>
    </tr>
    <tr>
      <th>ジャンル</th>
      <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_name),include_blank: "選択してください" %></td>
    </tr>
    <tr>
      <th>税抜価格</th>
      <td><%= f.number_field :price %>円</td>
    </tr>
    <tr>
      <th>販売ステータス</th>
      <td>
        <%= f.radio_button :sales_status, "sale" %>
        <%= f.label :sales_status_sale, "販売中" %>

        <%= f.radio_button :sales_status, "stop_sale" %>
        <%= f.label :sales_status_stop_sale, "販売停止中" %>
      </td>
    </tr>
    </table>
    <%= f.submit '新規登録',class: 'btn btn-success' %>
  <% end %>

  </div>
 </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto">

 <h4 class="mt-5 mb-4">商品詳細</h4>
  <table>
    <% if @item.image.attached? %>
     <%= image_tag @item.image,size:"200x200" %>
    <% else %>
     <%= image_tag 'no_image', size: "200x200" %>
    <% end %>
  <tr>
    <th>商品名</th>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <th>商品説明</th>
    <td><%= @item.introduction %></td>
  </tr>
  <tr>
    <th>税込価格<br>(税抜価格)</th>
    <td><%= @item.tax_included_price %>(<%= @item.price %>)円</td>
  </tr>
  <tr>
    <th>販売ステータス</th>
    <td><% if @item.sales_status == true %>
        <td class="text-success">販売中</td>
        <% else %>
        <td class="text-black-50">販売停止中</td>
        <% end %></td>
  </tr>
  </table>
  <span><%= link_to "編集する", edit_admin_item_path,class: 'btn btn-success' %></span>
 </div>
</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">

  <h4 class="mt-5 mb-4">注文履歴詳細</h4>
    <table>
      <tr>
        <th>購入者</th>
         <td><%= link_to @order.customer.last_name+@order.customer.first_name,admin_customer_path(@order.customer),class: 'text-dark' %></td>
      </tr>

      <tr>
        <th>注文日</th>
         <td><%= @order.created_at %></td>
      </tr>

      <tr>
        <th>配送先</th>
          <td><%= @order.delivery_postal_code %>
          <%= @order.delivery_address %></td>
          <td><%= @order.delivery_name %></td>
      </tr>

      <tr>
         <th>支払方法</th>
         <td><%= @order.payment_method_i18n %></td>
      </tr>
    </table>

    <table class="mt-4 w-100 table">
      <tr>
       <th>商品名</th>
       <th>単価（税込）</th>
       <th>数量</th>
       <th>小計</th>
       <th></th>
      </tr>
      <% @order_items.each do |order_item| %>
      <tr>
       <td><%= order_item.item.name %></td>
       <td><%= order_item.purchase_price %></td>
       <td><%= order_item.amount %></td>
       <td><%= order_item.subtotal %></td>
       <td></td>
       <% @total_price += order_item.subtotal %>
      </tr>
      <% end %>
      </table>

      <div class="text-right">商品合計 <%= @total_price %>円</div>
      <div class="text-right">送料 800円</div>
      <div class="text-right">請求金額 <%= @total_price + 800 %>円</div>
</div>