config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  root to:'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'admin' => 'admin/homes#top'

  # 管理者側のルーティング設定
  namespace :admin do
    # get 'items' => 'items#index'
    # post 'items' => 'items#create'
    # get 'items/new' => 'items#new'
    # get 'items/:id' => 'items#show'
    # get 'items/:id/edit' => 'items#edit'
    # patch 'items/:id' => 'items#update'
    resources :items,except:[:destroy]
  end

  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show]
    resources :genres,only: [:index,:create,:edit,:update]
  end

  scope module: :public do
  get 'customers/my_page' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/confirm_withdraw' => 'customers#confirm_withdraw'
  patch 'customers/withdraw' => 'customers#withdraw'
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/complete' => 'orders#complete'

  resources :items,only: [:index,:show]
  resources :cart_items,only: [:index,:create,:destroy,:update]
  resources :orders,only: [:index,:show,:create,:new]
  resources :addresses,only: [:index,:create,:edit,:destroy,:update]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items
  has_many :orders
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
has_many :items


end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  has_many :order_items
  belongs_to :genre
  # enum sales_status: { sale: true, stop_sale: false }

   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end

   TAX_RATE = 0.1
   def tax_included_price
    (price * (1 + TAX_RATE)).floor
   end

   def with_tax_price
       (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
      purchase_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @new_genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @item = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @item_new = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name,:image,:introduction,:price,:genre_id,:sales_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/app/admin_helper.rb
module App::AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">ながのCAKE</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
            <li class="nav-item">
            <%= link_to "ログアウト",destroy_admin_session_path,method: :delete,class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
            <%= link_to "ログイン",new_admin_session_path,class: 'nav-link text-dark' %>
            </li>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
     <%= yield %>
  </body>
</html>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">ながのCAKE</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
            <li class="nav-item">
            <%= link_to "商品一覧",admin_items_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "会員一覧",admin_customers_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "注文履歴一覧",admin_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "ジャンル一覧",admin_genres_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "ログアウト",destroy_admin_session_path,method: :delete,class: 'nav-link text-dark' %>
            </li>
            <% elsif customer_signed_in? %>
            <p class="text-center">ようこそ！<%= current_customer.last_name %>さん</p>
            <li class="nav-item">
            <%= link_to "マイページ",customers_my_page_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "商品一覧",items_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "カート",cart_items_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "ログアウト",destroy_customer_session_path,method: :delete,class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
            <%= link_to "About",about_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "商品一覧",items_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "新規登録",new_customer_registration_path,class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
            <%= link_to "ログイン",new_customer_session_path,class: 'nav-link text-dark' %>
            </li>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
     <%= yield %>
  </body>
</html>